### ISSUE TITLE
Import bug

### ISSUE THREAD

**Issue by jon-chuang** [thuml/depyf#1]
```
Traceback (most recent call last):
  File "/home/jonch/nested_graph_break.py", line 2, in <module>
    import depyf
  File "/home/jonch/.local/lib/python3.10/site-packages/depyf/__init__.py", line 54, in <module>
    __version__ = open(f"{os.path.dirname(__file__)}/VERSION.txt").read().strip()
FileNotFoundError: [Errno 2] No such file or directory: '/home/jonch/.local/lib/python3.10/site-packages/depyf/VERSION.txt'

```

**Comment by youkaichao** [comment]
Hi, sorry for the trouble. It should be fixed in https://github.com/thuml/depyf/commit/07661e5cb3a2b2818902fe1af5d640f76bfeb7fb . Could you please try it again?
