### ISSUE TITLE
RuntimeError: You cannot use `depyf.debug` inside `depyf.prepare_debug` on README.md debugger script

### ISSUE THREAD

**Issue by xmfan** [thuml/depyf#15]
On the latest 0.14 release, the README's last script for debugger use is broken

```
/home/xmfan/.conda/envs/empathy/lib/python3.10/site-packages/depyf/explain/enable_debugging.py:153: UserWarning: You are trying to debug `torch.compile`. Please make sure the code runs multiple times to cover all the possible branches.
  warnings.warn((
Traceback (most recent call last):
  File "/home/xmfan/depyf/main.py", line 21, in <module>
    with depyf.debug():
  File "/home/xmfan/.conda/envs/empathy/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/xmfan/.conda/envs/empathy/lib/python3.10/site-packages/depyf/explain/enable_debugging.py", line 221, in debug
    raise RuntimeError("You cannot use `depyf.debug` inside `depyf.prepare_debug`.")
RuntimeError: You cannot use `depyf.debug` inside `depyf.prepare_debug`.
```

<details>
  <summary>Repro (same as last script in README.md)</summary>
  
```
import torch
from torch import _dynamo as torchdynamo
from typing import List

@torch.compile
def toy_example(a, b):
    x = a / (torch.abs(a) + 1)
    if b.sum() < 0:
        b = b * -1
    return x * b

def main():
    for _ in range(100):
        toy_example(torch.randn(10), torch.randn(10))

if __name__ == "__main__":
    import depyf
    with depyf.prepare_debug("./dump_src_dir"):
        main()
    # surround the code you want to debug inside `with depyf.debug()`
    with depyf.debug():
        main()
```

</details>

**Comment by youkaichao** [comment]
Thanks, should be fixed now by [8c78c7c](https://github.com/thuml/depyf/commit/8c78c7cd773b3990e207696a3279e76467abdc80).
