### ISSUE TITLE
UnboundLocalError: local variable 'graph_out_0' referenced before assignment

### ISSUE THREAD

**Issue by xmfan** [thuml/depyf#18]
Happens on python3.10, pytorch nightly. Seems to happen due to depyf mishandling stack values:

Repro:
```python
import torch
import depyf

@torch.compile
def fn():
    x = torch.randn(1, 10, requires_grad=True)
    y = torch.randn(10, 1)
    loss = torch.mm(x, y).sum()
    loss.backward()
    return x.grad

with depyf.prepare_debug("./dump_src_dir"):
  fn()
```

Dynamo bytecode for torch_dynamo_resume_in_fn_at_6:
```python
DEBUG:torch._dynamo.convert_frame.__bytecode:MODIFIED BYTECODE torch_dynamo_resume_in_fn_at_6 /home/xmfan/core/pytorch/ca.py line 6 
  6           0 LOAD_GLOBAL              6 (__compiled_fn_5)
              2 LOAD_FAST                0 (___stack0)         
              4 CALL_FUNCTION            1
              6 STORE_FAST               4 (graph_out_0)
              8 LOAD_FAST                4 (graph_out_0)
             10 LOAD_CONST               5 (0)    
             12 BINARY_SUBSCR                  
             14 LOAD_ATTR                4 (backward)
             16 LOAD_FAST                0 (___stack0)
             18 STORE_FAST               1 (x)
             20 DELETE_FAST              4 (graph_out_0)  # deleted, but value is already in the stack
                                                                        
  9          22 CALL_FUNCTION            0    
             24 LOAD_GLOBAL              7 (__resume_at_54_6)
             26 ROT_TWO                   
             28 LOAD_FAST                1 (x)  
             30 CALL_FUNCTION            2
             32 RETURN_VALUE   
```

Depyf torch_dynamo_resume_in_fn_at_6:
```python
def __transformed_code_0_for_torch_dynamo_resume_in_fn_at_6(___stack0):
    loss = None; y = None # this line helps the compiler to generate bytecode with at least the same number of local variables as the original function

    graph_out_0 = __compiled_fn_5(___stack0)
    x = ___stack0
    del graph_out_0
    return __resume_at_54_6(graph_out_0[0].backward(), x)  # graph_out_0 already del'd
```

Traceback:
```python
Traceback (most recent call last):                                     
  File "/home/xmfan/core/pytorch/ca.py", line 13, in <module>                                                                                   
    fn()                                                                
  File "/home/xmfan/core/pytorch/torch/_dynamo/eval_frame.py", line 420, in _fn                                                                 
    return fn(*args, **kwargs)                                          
  File "/home/xmfan/core/pytorch/dump_src_dir/__transformed_code_0_for_fn.py", line 4, in __transformed_code_0_for_fn                                                                                                                                                                           
    return __resume_at_14_2(torch.randn(1, 10, requires_grad=True))                                                                             
  File "/home/xmfan/core/pytorch/dump_src_dir/__transformed_code_0_for_torch_dynamo_resume_in_fn_at_6.py", line 7, in __transformed_code_0_for_torch_dynamo_resume_in_fn_at_6                                                                                                                   
    return __resume_at_54_6(graph_out_0[0].backward(), x)                                                                                       
UnboundLocalError: local variable 'graph_out_0' referenced before assignment
```

**Comment by youkaichao** [comment]
Thanks for your interest! I will catch up latest pytorch nightly in recent days.

**Comment by youkaichao** [comment]
@xmfan can you try the latest main? It should be fixed now. The `DELETE_FAST` bytecode does not do `del` actually. It just decrease the reference count, and can be regarded as a non-op.

**Comment by xmfan** [comment]
Thanks for the fast fix!
